#!/usr/bin/env bash

set -euo pipefail
shopt -s dotglob nullglob
trap 'echo "${0} line ${LINENO} Status: ${?}"' ERR

export ARTIFACT=schema

clojure -A:dev:test
clojure -A:jar
mvn deploy:deploy-file \
    -Dfile=$ARTIFACT.jar \
    -DpomFile=pom.xml \
    -DrepositoryId=clojars \
    -Durl=https://clojars.org/repo/
rm $ARTIFACT.jar
